### PR TITLE
Fixes to update google_api_availability package dependency so that Kotlin support is removed.

### PR DESCRIPTION
**Pull request by slightfoot**
Fixes to update google_api_availability package dependency so that Kotlin support is removed so we can build for AndroidX.

### CODE REVIEW

**Comment by GiacomoK** [comment]
I guess we have to wait for official release, right?

**Comment by quiet324** [comment]
Waiting...

**Comment by slightfoot** [comment]
@mvanbeusekom I have this locally building fine. I assume this is a CI issue. Think you can look into getting this merged.

**Comment by rhalff** [comment]
@GiacomoK @quiet324 if you need to use this fix now, you can temporarily add the branch as a dependency:

```dart
  # geolocator: '^3.0.0'
  geolocator:
    git:
      url: git://github.com/slightfoot/flutter-geolocator.git
      ref: develop
```

**Comment by mvanbeusekom** [comment]
Same as #208 and #222

**Pull request closed without merging**
